CREATE TABLE Cities(
Id	INT	PRIMARY KEY IDENTITY,
[Name] NVARCHAR(20) NOT NULL,
CountryCode	CHAR(2)	NOT NULL
)

CREATE TABLE Hotels(
Id	INT	PRIMARY KEY IDENTITY,
[Name]	NVARCHAR(30) NOT NULL,
CityId	INT NOT NULL,
EmployeeCount INT NOT NULL,
BaseRate DECIMAL(16,2)	

CONSTRAINT FK_CityId1 FOREIGN KEY (CityId) REFERENCES Cities(Id)
)

CREATE TABLE Rooms(
Id	INT	PRIMARY KEY IDENTITY,
Price DECIMAL(16,2)	NOT NULL,
[Type] NVARCHAR(20) NOT NULL,
Beds INT NOT NULL,
HotelId	INT NOT NULL

CONSTRAINT FK_HotelId FOREIGN KEY (HotelId) REFERENCES Hotels(Id)
)

CREATE TABLE Trips(
Id	INT	PRIMARY KEY IDENTITY,
RoomId	INT NOT NULL,
BookDate DATE NOT NULL,
ArrivalDate	DATE NOT NULL,
ReturnDate	DATE NOT NULL,
CancelDate	DATE,

CONSTRAINT CHK_Dates CHECK (BookDate < ArrivalDate), CHECK(ArrivalDate <= ReturnDate),

CONSTRAINT FK_RoomId FOREIGN KEY (RoomId) REFERENCES Rooms(Id)
)	

CREATE TABLE Accounts(
Id	INT	PRIMARY KEY IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
MiddleName NVARCHAR(20),	
LastName NVARCHAR(50) NOT NULL,
CityId	INT NOT NULL,
BirthDate DATE NOT NULL,
Email VARCHAR(100) UNIQUE NOT NULL


CONSTRAINT FK_CityId2 FOREIGN KEY (CityId) REFERENCES Cities(Id)
)

CREATE TABLE AccountsTrips(
AccountId INT FOREIGN KEY REFERENCES Accounts(Id) NOT NULL,
TripId INT FOREIGN KEY REFERENCES Trips(Id) NOT NULL,
Luggage	INT CHECK(Luggage >= 0) DEFAULT 0

CONSTRAINT PK_AkTr PRIMARY KEY (AccountId, TripId)
)