CREATE TABLE Subjects(
SubjectID INT PRIMARY KEY IDENTITY,
SubjectName VARCHAR(100)
)

CREATE TABLE Majors(
MajorID INT PRIMARY KEY IDENTITY,
Name VARCHAR (100)
)

CREATE TABLE Students(
StudentID INT PRIMARY KEY IDENTITY,
StudentNumber CHAR(8) NOT NULL,
StudentName VARCHAR(50) NOT NULL,
MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)
)

CREATE TABLE Agenda(
StudentID INT FOREIGN KEY REFERENCES Students(StudentID),
SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID)
PRIMARY KEY(StudentID, SubjectID)
)

CREATE TABLE Payments(
PaymentID INT PRIMARY KEY IDENTITY,
PaymentDate DATE,
PaymentAmount DECIMAL(8, 2),
StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
)