ALTER TABLE Users
DROP CONSTRAINT PK_Users;

ALTER TABLE Users
ADD CONSTRAINT PK_UserId PRIMARY KEY (Id);

ALTER TABLE Users
ADD CONSTRAINT UniqueUsers
UNIQUE(Username)

ALTER TABLE Users
ADD CHECK (LEN(Username) >=3);