CREATE DATABASE SoftUni

CREATE TABLE Towns(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Name VARCHAR(50)
)

CREATE TABLE Addresses(
Id INT PRIMARY KEY IDENTITY NOT NULL,
AddressText VARCHAR(500),
TownId INT FOREIGN KEY REFERENCES Towns(Id)
)

CREATE TABLE Departments(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Name VARCHAR(50)
)

CREATE TABLE Employees(
Id INT PRIMARY KEY IDENTITY NOT NULL,
FirstName VARCHAR(50),
MiddleName VARCHAR(50),
LastName VARCHAR(50),
JobTitle VARCHAR(50),
DepartmentId INT FOREIGN KEY REFERENCES Departments(Id),
HireDate DATE,
Salary DECIMAL(7, 2),
AddressId INT FOREIGN KEY REFERENCES Addresses(Id)
)