CREATE TABLE Categories(
Id	INT	PRIMARY KEY IDENTITY,
[Name]	NVARCHAR(30) NOT NULL
)

CREATE TABLE Items(
Id	INT	PRIMARY KEY IDENTITY,
[Name] NVARCHAR(30) NOT NULL,
Price DECIMAL(16,2)	NOT NULL,
CategoryId	INT	NOT NULL

CONSTRAINT FK_CategoryId FOREIGN KEY (CategoryId) REFERENCES Categories(Id)
)

CREATE TABLE Employees(
Id	INT	PRIMARY KEY IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
Phone CHAR(12) NOT NULL,
Salary	DECIMAL(16,2) NOT NULL
)

CREATE TABLE Orders(
Id	INT	PRIMARY KEY IDENTITY,
DateTime DATETIME NOT NULL,
EmployeeId INT NOT NULL

CONSTRAINT FK_EmployeeIdd FOREIGN KEY (EmployeeId) REFERENCES Employees(Id)
)

CREATE TABLE OrderItems(
OrderId	INT NOT NULL FOREIGN KEY REFERENCES Orders(Id),
ItemId	INT NOT NULL FOREIGN KEY REFERENCES Items(Id),
Quantity INT NOT NULL CHECK(Quantity >= 1)

CONSTRAINT PK_OrIt PRIMARY KEY (OrderId, ItemId)
)

CREATE TABLE Shifts(
Id	INT IDENTITY,
EmployeeId INT FOREIGN KEY REFERENCES Employees(Id),
CheckIn	DATETIME NOT NULL,
CheckOut DATETIME NOT NULL --, must be after CheckIn date

CONSTRAINT PK_IdEm PRIMARY KEY (Id, EmployeeId)
)